### ISSUE TITLE
stable output identifiers

### ISSUE THREAD

**Issue by colemickens** [atomnuker/wlstream#5]
The identifier numbers used for outputs are not stable over time, either due to machine or compositor restarts. It would be good if this tool allowed specifying a stable identifier for the output.

**Comment by schauveau** [comment]
I assume that it is possible to obtain the geometry of each output by combining the event information: x and y from output_handle_geometry(), width and height from output_handle_mode() and factor from output_handle_scale(). 
If so, the screen could be selected by specifying the coordinate of a single point. 
Eventually, the program should be able to encode a given region using slurm.

**Comment by colemickens** [comment]
In my opinion, that's a bigger, separate feature. My problem is much simpler and is one that has been solved previously in sway and probably is a relatively small delta. My problem is simply that a given monitor will have a different output identifier number on different runs of the program in different sway sessions. This same issue affected the sway config file and is solved now by supporting a stable identifier that always refers to a specific monitor.

**Comment by atomnuker** [comment]
https://github.com/atomnuker/wlstream/issues/10#issuecomment-478739185
