### ISSUE TITLE
add build explanation

### ISSUE THREAD

**Issue by shibumi** [atomnuker/wlstream#7]
Hi,
would be nice to have a explanation on how to build this.

**Comment by levimake** [comment]
## Installation
```
build meson
ninja -C build
sudo ninja -C build install
```

### Usage
```
wlstream  <source id> <hardware device type> <device> <encoder name> <pixel format> <bitrate in Mbps> <file path>
```
### Example
```
wlstream 24 vaapi /dev/dri/renderD128 libx264 nv12 12 output.mkv
```

**Comment by shioyama** [comment]
If anybody on arch is looking to save a few keystrokes, here's an AUR package I just made for this:

https://aur.archlinux.org/packages/wlstream-git/

**Comment by schauveau** [comment]
A few more tips:

libx264 is a software encoder so if your system supports vaapi encoding (see https://wiki.libav.org/Hardware/vaapi ) then you can replace `libx264` by `h264_vaapi`, `vp8_vaapi` or `hevc_vaapi`. 
The encoding quality may not be better but wlstream should use less CPU.

The encoder can be stopped manually with CTRL-C or by sending signal 2 (via kill, killall, ...). 
On Debian, the `timeout` command from the coreutils package can be used to automatically stop recording after a given delay:
```
# record during 5 seconds using h264 HW encoding: 
timeout -s INT 5  ./build/src/wlstream 28 vaapi /dev/dri/renderD128 h264_vaapi  nv12 100 out.mkv 
```

**Comment by atomnuker** [comment]
https://github.com/atomnuker/wlstream/issues/10#issuecomment-478739185
